### PR TITLE
feat: sets a check run start time

### PR DESCRIPTION
**Pull request by anjakammer**
Until now, all check runs ran for under 5 seconds according to GitHub since the start and end time was almost the same.

### CODE REVIEW

**Comment by radu-matei** [comment]
I've been silently annoyed by this for a very long time..

**Comment by anjakammer** [comment]
Does somebody want to review this? @radu-matei

**Comment by radu-matei** [comment]
I built this and used it for a test, and still see _in less than 5 seconds_:

image


Did you actually see different results?
Thanks!

**Comment by anjakammer** [comment]
If you are setting the environment variable, it works.
image

```javascript
    this.env = {
      CHECK_PAYLOAD: payload,
      CHECK_NAME: stage,
      CHECK_TITLE: title,
      CHECK_CONCLUSION: conclusion,
      CHECK_SUMMARY: summery,
      CHECK_TEXT: logs,
      CHECK_STARTED_AT: startedAt
    }
```

**Pull request merged**
